server:
  port: 9000
  
eureka:
  instance:
    hostname: localhost
    
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
      - id: staff-service
        uri:
          http://localhost:9001
        predicates:
        - Path=/grocery/api/staff/**
      - id: PRODUCT-SERVICE
        uri:
          http://localhost:9002
        predicates:
        - Path=/grocery/api/product/**
      - id: LOGIN-SERVICE 
        uri:
          http://localhost:9003
        predicates:
        - Path=/grocery/api/login/**
      - id: customer-service
        uri:
          http://localhost:9004
        predicates:
        - Path=/grocery/api/customer/**
      
            
    
  
